# Numerical CBF Configuration (cbf_config.yaml)
run_mode: single
model_type: NumericalCBF
project_name: recommender-evaluation
experiment_name: cbf_experiment
description: "Content-based filtering evaluation"